import assert from "node:assert/strict";
import { generateKeyPairSync } from "node:crypto";
import test from "node:test";
import { verifyAuditSegment } from "../src/audit/hash-chain.js";
import { loadProductionConfig } from "../src/production/config.js";
import { ProductionHttpsTransport, type AddressResolver, type SecretValueResolver } from "../src/production/network-transport.js";
import { evaluateProductionReadiness } from "../src/production/readiness.js";
import { AgentRuntime } from "../src/runtime/agent-runtime.js";
import { ExecutorRegistry } from "../src/runtime/executor-registry.js";

const publicResolver: AddressResolver = {
  async resolve() {
    return [{ address: "93.184.216.34", family: 4 }];
  },
};

function productionEnv(): Record<string, string> {
  const { publicKey } = generateKeyPairSync("ed25519");
  return {
    AIA_AGENT_ID: "advanced-uat-agent",
    AIA_AGENT_DISPLAY_NAME: "Authorized AI Representative",
    AIA_OWNER_REFERENCE: "owner:primary",
    AIA_AGENT_DISCLOSURE: "AI representative acting under owner authorization.",
    AIA_OWNER_KEY_ID: "owner-key-advanced-uat",
    AIA_OWNER_PUBLIC_KEY_PEM: publicKey.export({ type: "spki", format: "pem" }).toString(),
    AIA_BUDGET_LIMIT_MINOR: "100000",
    AIA_BUDGET_CURRENCY: "TRY",
    AIA_ALLOWED_ORIGINS: "https://api.example.com",
    AIA_CHECKPOINT_PATH: "/tmp/aia-advanced-uat-checkpoint.json",
  };
}

test("A-05: runtime returns per-run audit events and retains a bounded verifiable audit window", async () => {
  const registry = new ExecutorRegistry();
  registry.register("content.draft", async (input) => input);
  const runtime = new AgentRuntime(registry, { maxRetainedAuditEvents: 3 });

  for (let index = 0; index < 3; index += 1) {
    const result = await runtime.run({
      taskId: `audit-task-${index}`,
      actionId: `audit-action-${index}`,
      capability: "content.draft",
      input: { index },
    });
    assert.equal(result.status, "succeeded");
    assert.equal(result.audit.length, 2, "run() must return only events generated by that run");
  }

  const window = runtime.getAuditWindow();
  assert.equal(window.events.length, 3, "retained audit history must respect the configured bound");
  assert.equal(window.base.eventCount, 3);
  assert.equal(window.head.eventCount, 6);
  assert.equal(verifyAuditSegment(window.events, window.base, window.head), true);
});

test("A-08: executor cannot mutate the caller task input by reference", async () => {
  const registry = new ExecutorRegistry();
  registry.register("product.build", async (input) => {
    (input as { injected?: string }).injected = "executor mutation";
    return input;
  });
  const runtime = new AgentRuntime(registry);
  const input = { safe: true };

  const result = await runtime.run({
    taskId: "clone-task",
    actionId: "clone-action",
    capability: "product.build",
    input,
  });

  assert.equal(result.status, "succeeded");
  assert.deepEqual(input, { safe: true });
  assert.deepEqual(result.output, { safe: true, injected: "executor mutation" });
});

test("A-06: direct transport construction rejects CRLF credential prefixes", () => {
  assert.throws(() => new ProductionHttpsTransport({
    allowedOrigins: ["https://api.example.com"],
    credentialBindings: [{
      origin: "https://api.example.com",
      header: "authorization",
      prefix: "Bearer \r\nX-Admin-Override: true\r\n",
      secret: { provider: "environment", name: "AIA_PROVIDER_TOKEN" },
    }],
  }), /prefix is invalid/i);
});

test("A-06: combined credential header is rejected when resolved secret contains CRLF", async () => {
  const secretResolver: SecretValueResolver = {
    async resolve() {
      return "safe-token\r\nX-Evil: true";
    },
  };
  const transport = new ProductionHttpsTransport({
    allowedOrigins: ["https://api.example.com"],
    resolver: publicResolver,
    secretResolver,
    credentialBindings: [{
      origin: "https://api.example.com",
      header: "authorization",
      prefix: "Bearer ",
      secret: { provider: "environment", name: "AIA_PROVIDER_TOKEN" },
    }],
    requester: async () => ({ status: 200, body: "should-not-run" }),
  });

  await assert.rejects(() => transport.send({
    method: "GET",
    url: "https://api.example.com/v1",
    timeoutMs: 1000,
    maxResponseBytes: 1024,
  }), /credential is invalid/i);
});

test("A-07: environment configuration rejects non-443 origins before readiness", () => {
  assert.throws(() => loadProductionConfig({
    ...productionEnv(),
    AIA_ALLOWED_ORIGINS: "https://api.example.com:8443",
  }), /unsupported HTTPS port 8443/i);
});

test("A-07: manually constructed non-443 config cannot report ready", () => {
  const config = loadProductionConfig(productionEnv());
  const report = evaluateProductionReadiness({
    ...config,
    allowedOrigins: ["https://api.example.com:8443"],
  }, new Date("2026-09-02T12:00:00.000Z"));

  assert.equal(report.status, "not_ready");
  assert.equal(report.checks.find((item) => item.name === "authorized_origins")?.ok, false);
});

test("A-07: direct transport rejects an allowed origin whose port is not in allowedPorts", () => {
  assert.throws(() => new ProductionHttpsTransport({
    allowedOrigins: ["https://api.example.com:8443"],
  }), /port 8443.*not allowed/i);
});
